language: node_js
node_js:
- 6
script:
- printf 'configs/\nsrc/\n.npmignore\n.travis.yml\nCHANGELOG.md\nGruntfile.js\nbower.json\nLICENSE-MIT\npackage.json\nnode_modules/\n.gitignore\ndeployed*' > .gitignore
- printf '.npmignore\n.travis.yml\nCNAME' > .npmignore
- printf 'jumboslider.martinmetodiev.com' > CNAME
branches:
  only:
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
deploy:
- provider: npm
  email: metodiev.martin@gmail.com
  api_key:
    secure: PYmKwO3MaggTkgoBwEenpccsjCu1pru07mgCDiuOiiCmvoj4gqmAJNcOka5BcPxyaILvM/XiGeIkUzkF9WAh14hbxlh0ct2OWRjPlgPN69jZslBH/3P1WW+3RkhpxQd+OJKwVxwO8gCRL72YWGHMF0vvmz7E0BT3kQuRfQpw9JTXyU/DDy81COsNBmJu00lgo+kk9/oTACz2yN1rw4elGXW/RLwsqCS4yMdDDeRRI2BbG0gj1dHWxGST7FNIu8MdP7gQl79HQiC1o5sY0dpZXInA4TKbWbq94ZmQQHPUkiAYMhxNtf1pMZTPyZoOu7ZvSImDssusuwA8DTxBeh6c4UkPTpCZXqxtE5l8oQTLkgxbMfCfmIs64DEdvsamjCLCGtRvYTrKKcxlI4qyX7DOFqNx1ktofX/kjRC+5YdB+eSsYQlhwUh4BrRRIxTNMM1WyEKrqVYJsAkAKkSru9YSRp6fU7RszHMVHWUH9asezgcRblPjFzl6ayW8Ez/krISiAQxMh5Wj+1xEcdmaTON1xaJeoLXuX6x+rB8TOZ79mp5TEFikWHN2WcAd0ZHdS/kGpXpcM4Ambg284b26joU9sHOt34ceJAweG7wI3eVS7x3UHpSUDedhzNoP55GJw7orlL1mmHDdTO680BAYVo3xNLaqSNvzhlIFUhvNkvTiyTQ=
  on:
    tags: true
- provider: pages
  skip_cleanup: true
  github_token:
    secure: MSrA6gS2dbQYrHLdaYj/L/i9/+RPQ1g2CBaNCF39vZ1ffPqLjjuGzxYFPKvik1vf38jffn0/HDJJDbqDQzm6GLg0viLn84w9h7XqobGID9AIPw7vBv+YzhSsMhJ/XHnu8BXQnoyX/ARhzFk0F4k1l27qgQ51tMep01BTGnMt53RLK15DwjeMPqfFUFQtQxoS0Ezo8GtzmJqqjY/hWG/rax5KJZTmbwNc4pmQ/qj2dbqOl8oh36eaWLyngp311taGWK9lKWBCDr0tIc+COLfrAxcoUzcEBmE0J+6KEF0OsMvFTd5kKVVsyElBwuZPfRrsc+n/VdHidVmRjGatcjs0mJfXVKEHkOqXNnTv7gVKUZNEEdehCq0JCczYeMykTvLzfKvSNO+FqxnGCHrLXS1KDg/RMnz/fMNPy4HE/heDChRoIY4fQviMr1YxdTpAOO25zRWgI4VV24nHD59oShUdjHnoyst0WGlXDEQRsf/6kfWA5Dz2XL+GRGc8emYrFDfLNdmAGIjA8YqnrphMjlInHmY+aO+aylDK9vEInqdr+mEmZoZJ8T1DFHXytGbG3WZIktVc1hbzTN9qyQ30rkOVX6AqyLgxSP0b4t0ZrmWZHFjtIpQef72cTVFu0DsH4om3EcruYkvtyy/m3GCF1b/K6VDspg5ZV3PLiYu14dBFv8I=
  on:
    tags: true
- provider: releases
  api_key:
    secure: MSrA6gS2dbQYrHLdaYj/L/i9/+RPQ1g2CBaNCF39vZ1ffPqLjjuGzxYFPKvik1vf38jffn0/HDJJDbqDQzm6GLg0viLn84w9h7XqobGID9AIPw7vBv+YzhSsMhJ/XHnu8BXQnoyX/ARhzFk0F4k1l27qgQ51tMep01BTGnMt53RLK15DwjeMPqfFUFQtQxoS0Ezo8GtzmJqqjY/hWG/rax5KJZTmbwNc4pmQ/qj2dbqOl8oh36eaWLyngp311taGWK9lKWBCDr0tIc+COLfrAxcoUzcEBmE0J+6KEF0OsMvFTd5kKVVsyElBwuZPfRrsc+n/VdHidVmRjGatcjs0mJfXVKEHkOqXNnTv7gVKUZNEEdehCq0JCczYeMykTvLzfKvSNO+FqxnGCHrLXS1KDg/RMnz/fMNPy4HE/heDChRoIY4fQviMr1YxdTpAOO25zRWgI4VV24nHD59oShUdjHnoyst0WGlXDEQRsf/6kfWA5Dz2XL+GRGc8emYrFDfLNdmAGIjA8YqnrphMjlInHmY+aO+aylDK9vEInqdr+mEmZoZJ8T1DFHXytGbG3WZIktVc1hbzTN9qyQ30rkOVX6AqyLgxSP0b4t0ZrmWZHFjtIpQef72cTVFu0DsH4om3EcruYkvtyy/m3GCF1b/K6VDspg5ZV3PLiYu14dBFv8I=
  skip_cleanup: true
  on:
    tags: true
